//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.UnitId;
import org.thespheres.betula.gpuntis.xml.Department.DepartmentRef;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;
import org.thespheres.betula.gpuntis.xml.Teacher.TeacherRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Class {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String longname;
    protected String alias;
    @XmlElement(name = "class_teacher")
    protected TeacherRef classTeacher;
    @XmlElement(name = "class_room")
    protected RoomRef classRoom;
    protected String classlevel;
    protected String studentsmale;
    protected String studentsfemale;
    protected String text;
    protected String begindate;
    protected String enddate;
    protected String flags;
    @XmlElement(name = "class_description")
    protected DescriptionRef classDescription;
    @XmlElement(name = "class_department")
    protected DepartmentRef classDepartment;
    protected String foreignkey;
    protected String lessonstable;
    @XmlElement(name = "unit", namespace = "http://www.thespheres.org/xsd/betula/betula.xsd")
    protected UnitId mappedUnit;

    public String getId() {
        return id;
    }

    public String getLongname() {
        return longname;
    }

    public String getAlias() {
        return alias;
    }

    public Teacher getClassTeacher() {
        return classTeacher != null ? classTeacher.get() : null;
    }

    public Room getClassRoom() {
        return classRoom != null ? classRoom.get() : null;
    }

    public String getClasslevel() {
        return classlevel;
    }

    public String getMaleStudents() {
        return studentsmale;
    }

    public String getFemalStudents() {
        return studentsfemale;
    }

    public String getText() {
        return text;
    }

    public String getBeginDate() {
        return begindate;
    }

    public String getEndDate() {
        return enddate;
    }

    public String getFlags() {
        return flags;
    }

    public Description getClassDescription() {
        return classDescription != null ? classDescription.get() : null;
    }

    public Department getClassDepartment() {
        return classDepartment != null ? classDepartment.get() : null;
    }

    public String getForeignKey() {
        return foreignkey;
    }

    public String getLessonsTable() {
        return lessonstable;
    }

    public UnitId getMappedUnit() {
        return mappedUnit;
    }

    public void setMappedUnit(UnitId unit) {
        this.mappedUnit = unit;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClassRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Class clasz;

        public Class get() {
            return clasz;
        }

    }
}
