//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Department.DepartmentRef;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;
import org.thespheres.betula.gpuntis.xml.Teacher.TeacherRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Class {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String longname;
    protected String alias;
    @XmlElement(name = "class_teacher")
    protected TeacherRef classTeacher;
    @XmlElement(name = "class_room")
    protected RoomRef classRoom;
    protected String classlevel;
    protected String studentsmale;
    protected String studentsfemale;
    protected String text;
    protected String begindate;
    protected String enddate;
    protected String flags;
    @XmlElement(name = "class_description")
    protected DescriptionRef classDescription;
    @XmlElement(name = "class_department")
    protected DepartmentRef classDepartment;
    protected String foreignkey;
    protected String lessonstable;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLongname() {
        return longname;
    }

    /**
     * Gets the value of the alias property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Gets the value of the classTeacher property.
     *
     * @return possible object is {@link ClassTeacher }
     *
     */
    public Teacher getClassTeacher() {
        return classTeacher != null ? classTeacher.get() : null;
    }

    /**
     * Gets the value of the classRoom property.
     *
     * @return possible object is {@link ClassRoom }
     *
     */
    public Room getClassRoom() {
        return classRoom != null ? classRoom.get() : null;
    }

    /**
     * Gets the value of the classlevel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getClasslevel() {
        return classlevel;
    }

    /**
     * Gets the value of the studentsmale property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStudentsmale() {
        return studentsmale;
    }

    /**
     * Gets the value of the studentsfemale property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStudentsfemale() {
        return studentsfemale;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the begindate property.
     *
     * @return possible object is {@link Begindate }
     *
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * Gets the value of the enddate property.
     *
     * @return possible object is {@link Enddate }
     *
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * Gets the value of the flags property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFlags() {
        return flags;
    }

    /**
     * Gets the value of the classDescription property.
     *
     * @return possible object is {@link ClassDescription }
     *
     */
    public Description getClassDescription() {
        return classDescription != null ? classDescription.get() : null;
    }

    /**
     * Gets the value of the classDepartment property.
     *
     * @return possible object is {@link ClassDepartment }
     *
     */
    public Department getClassDepartment() {
        return classDepartment != null ? classDepartment.get() : null;
    }

    /**
     * Gets the value of the foreignkey property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForeignkey() {
        return foreignkey;
    }

    /**
     * Gets the value of the lessonstable property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLessonstable() {
        return lessonstable;
    }

    /**
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClassRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Class clasz;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Class get() {
            return clasz;
        }

    }
}
