//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import org.thespheres.betula.gpuntis.xml.util.TimeSecondAdapter;
import org.thespheres.betula.gpuntis.xml.util.DateAdapter;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "document")
public class Document {

    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "date")
    @XmlJavaTypeAdapter(DateAdapter.class)
    protected LocalDate date;
    @XmlAttribute(name = "time")
    @XmlJavaTypeAdapter(TimeSecondAdapter.class)
    protected LocalTime time;
    @XmlElement(name = "general")
    protected General general;
    @XmlElementWrapper(name = "timeperiods")
    @XmlElement(name = "timeperiod")
    protected List<Timeperiod> timeperiods = new ArrayList<>();
    @XmlElementWrapper(name = "descriptions")
    @XmlElement(name = "description")
    protected List<Description> descriptions = new ArrayList<>();
    @XmlElementWrapper(name = "departments")
    @XmlElement(name = "department")
    protected List<Department> departments = new ArrayList<>();
    @XmlElementWrapper(name = "rooms")
    @XmlElement(name = "room")
    protected List<Room> rooms = new ArrayList<>();
    @XmlElementWrapper(name = "subjects")
    @XmlElement(name = "subject")
    protected List<Subject> subjects = new ArrayList<>();
    @XmlElementWrapper(name = "teachers")
    @XmlElement(name = "teacher")
    protected List<Teacher> teachers = new ArrayList<>();
    @XmlElementWrapper(name = "classes")
    @XmlElement(name = "class")
    protected List<Class> classes = new ArrayList<>();
    @XmlElementWrapper(name = "students")
    @XmlElement(name = "student")
    protected List<Student> students = new ArrayList<>();
    @XmlElementWrapper(name = "terms")
    @XmlElement(name = "term")
    protected List<Term> terms = new ArrayList<>();
    @XmlElementWrapper(name = "lessons")
    @XmlElement(name = "lesson")
    protected List<Lesson> lessons = new ArrayList<>();
    @XmlElementWrapper(name = "reductions")
    @XmlElement(name = "reduction")
    protected List<Reduction> reductions = new ArrayList<>();

    public String getVersion() {
        return version;
    }

    public LocalDate getDate() {
        return date;
    }

    public LocalTime getTime() {
        return time;
    }

    public General getGeneral() {
        return general;
    }

    public List<Timeperiod> getTimeperiods() {
        return timeperiods;
    }

    public List<Description> getDescriptions() {
        return descriptions;
    }

    public List<Department> getDepartments() {
        return departments;
    }

    public List<Room> getRooms() {
        return rooms;
    }

    public List<Subject> getSubjects() {
        return subjects;
    }

    public List<Teacher> getTeachers() {
        return teachers;
    }

    public List<Class> getClasses() {
        return classes;
    }

    public List<Student> getStudents() {
        return students;
    }

    public List<Term> getTerms() {
        return terms;
    }

    public List<Lesson> getLessons() {
        return lessons;
    }

    public List<Reduction> getReductions() {
        return reductions;
    }

}
