//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import org.thespheres.betula.gpuntis.xml.util.DateAdapter;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;
import org.thespheres.betula.gpuntis.xml.Subject.SubjectRef;
import org.thespheres.betula.gpuntis.xml.Teacher.TeacherRef;
import org.thespheres.betula.gpuntis.xml.Term.TermRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Lesson {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElement(required = true)
    protected String periods;
    @XmlElement(name = "lesson_subject")
    protected SubjectRef lessonSubject;
    @XmlElement(name = "lesson_teacher")
    protected TeacherRef lessonTeacher;
    @XmlElement(name = "lesson_classes")
    protected LessonClasses lessonClasses;
    @XmlElement(name = "lesson_studentgroups")
    protected LessonStudentgroups lessonStudentgroups;
    @XmlElement(name = "lesson_students")
    protected LessonStudents lessonStudents;
    @XmlElement(name = "lesson_room")
    protected RoomRef lessonRoom;
    @XmlElement(name = "lesson_term")
    protected TermRef term;
    protected String begindate;
    protected String enddate;
    @XmlJavaTypeAdapter(DateAdapter.class)
    @XmlElement(name = "effectivebegindate")
    protected LocalDate effectivebegindate;
    @XmlJavaTypeAdapter(DateAdapter.class)
    @XmlElement(name = "effectiveenddate")
    protected LocalDate effectiveenddate;
    protected String week;
    protected String block;
    protected String occurence;
    protected String text;
    protected String text1;
    protected String text2;
    protected String flags;
    protected String foreignkey;
    @XmlElementWrapper(name = "times")
    @XmlElement(name = "time")
    protected List<Time> times = new ArrayList<>();
    @XmlElement(name = "lesson_description")
    protected DescriptionRef lessonDescription;
    @XmlElement(name = "teacher_value")
    protected String teacherValue;
    @XmlElement(name = "timegrid")
    protected String timegrid;

    public String getId() {
        return id;
    }

    public String getPeriods() {
        return periods;
    }

    public Subject getLessonSubject() {
        return lessonSubject != null ? lessonSubject.get() : null;
    }

    public Teacher getLessonTeacher() {
        return lessonTeacher != null ? lessonTeacher.get() : null;
    }

    public List<Class> getLessonClasses() {
        return lessonClasses != null ? lessonClasses.getClasses() : null;
    }

    public LessonStudentgroups getLessonStudentgroups() {
        return lessonStudentgroups;
    }

    public LessonStudents getLessonStudents() {
        return lessonStudents;
    }

    public Room getLessonRoom() {
        return lessonRoom != null ? lessonRoom.get() : null;
    }

    public LocalDate getEffectiveBeginDate() {
        return effectivebegindate;
    }

    public LocalDate getEffectiveEndDate() {
        return effectiveenddate;
    }

    public String getWeek() {
        return week;
    }

    public String getBlock() {
        return block;
    }

    public String getOccurence() {
        return occurence;
    }

    public String getText() {
        return text;
    }

    public String getText1() {
        return text1;
    }

    public String getText2() {
        return text2;
    }

    public String getFlags() {
        return flags;
    }

    public String getForeignkey() {
        return foreignkey;
    }

    public List<Time> getTimes() {
        return times;
    }

    public Description getLessonDescription() {
        return lessonDescription != null ? lessonDescription.get() : null;
    }

    public String getTeacherValue() {
        return teacherValue;
    }

    public String getTimegrid() {
        return timegrid;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Lesson other = (Lesson) obj;
        return Objects.equals(this.id, other.id);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    public static class LessonStudents {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected List<Student> id = new ArrayList<>();

        /**
         * Gets the value of the id property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the id property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getId().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
     * {@link Object }
         *
         *
         * @return
         */
        public List<Student> getId() {
            return this.id;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    public static class LessonStudentgroups {

        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String id;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getId() {
            return id;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    public static class LessonClasses {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        @XmlList
        protected List<Class> clzes;

//        @XmlAttribute(name = "id", required = true)
////        @XmlList
////        @XmlIDREF
//        protected Ref ids;// = new ArrayList<>();
        /**
         * Gets the value of the id property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the id property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getId().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
     * {@link Object }
         *
         *
         * @return
         */
        public List<Class> getClasses() {
            if (clzes == null) {
//                clzes = ids.stream().map((ref) -> ref.clz).collect(Collectors.toList());
            }
            return clzes;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    public static class Ref {

        @XmlList
        @XmlValue
//        @XmlIDREF
        protected List<String> ids = new ArrayList<>();
    }
}
