//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//


package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Teacher.TeacherRef;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Reduction {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElement(name = "reduction_teacher")
    protected TeacherRef reductionTeacher;
//    @XmlElement(name = "reduction_reason")
//    protected ReductionReason reductionReason;
    protected String value;
    protected String text;
    protected String begindate;
    protected String enddate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the reductionTeacher property.
     * 
     * @return
     *     possible object is
     *     {@link ReductionTeacher }
     *     
     */
    public Teacher getReductionTeacher() {
        return reductionTeacher != null ? reductionTeacher.get() : null;
    }

//    /**
//     * Gets the value of the reductionReason property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link ReductionReason }
//     *     
//     */
//    public ReductionReason getReductionReason() {
//        return reductionReason;
//    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the begindate property.
     * 
     * @return
     *     possible object is
     *     {@link Begindate }
     *     
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link Enddate }
     *     
     */
    public String getEnddate() {
        return enddate;
    }

}
