//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Department.DepartmentRef;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Room {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String longname;
    protected String capacity;
    protected String text;
    protected String flags;
    @XmlElement(name = "room_description")
    protected DescriptionRef roomDescription;
    @XmlElement(name = "room_department")
    protected DepartmentRef roomDepartment;
    protected String foreignkey;
    @XmlElement(name = "external_name")
    protected String externalName;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLongname() {
        return longname;
    }

    /**
     * Gets the value of the capacity property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the flags property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFlags() {
        return flags;
    }

    /**
     * Gets the value of the roomDescription property.
     *
     * @return possible object is {@link RoomDescription }
     *
     */
    public Description getRoomDescription() {
        return roomDescription != null ? roomDescription.get() : null;
    }

    /**
     * Gets the value of the roomDepartment property.
     *
     * @return possible object is {@link RoomDepartment }
     *
     */
    public Department getRoomDepartment() {
        return roomDepartment != null ? roomDepartment.get() : null;
    }

    /**
     * Gets the value of the foreignkey property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForeignkey() {
        return foreignkey;
    }

    /**
     * Gets the value of the externalName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RoomRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Room room;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Room get() {
            return room;
        }

    }
}
