//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Class.ClassRef;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "student", namespace = "https://untis.at/untis/XmlInterface")
public class Student {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String forename;
    protected String surname;
    protected String gender;
    protected String birthdate;
    protected String idnumber;
    protected String email;
    @XmlElement(name = "student_class", required = true)
    protected ClassRef studentClass;
    protected String text;
    protected String flags;
    @XmlElement(name = "student_description")
    protected DescriptionRef studentDescription;
    protected String foreignkey;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the forename property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForename() {
        return forename;
    }

    /**
     * Gets the value of the surname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGender() {
        return gender;
    }

    /**
     * Gets the value of the birthdate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * Gets the value of the idnumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     * Gets the value of the studentClass property.
     *
     * @return possible object is {@link StudentClass }
     *
     */
    public Class getStudentClass() {
        return studentClass != null ? studentClass.get() : null;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the flags property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFlags() {
        return flags;
    }

    /**
     * Gets the value of the studentDescription property.
     *
     * @return possible object is {@link StudentDescription }
     *
     */
    public Description getStudentDescription() {
        return studentDescription != null ? studentDescription.get() : null;
    }

    /**
     * Gets the value of the foreignkey property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForeignkey() {
        return foreignkey;
    }

}
