//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Subject {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String longname;
    protected String alias;
    protected String text;
    protected String subjectgroup;
    @XmlElement(name = "subject_room")
    protected RoomRef subjectRoom;
    protected String flags;
    @XmlElement(name = "subject_description")
    protected DescriptionRef subjectDescription;
    protected String foreignkey;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the longname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLongname() {
        return longname;
    }

    /**
     * Gets the value of the alias property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Gets the value of the subjectgroup property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSubjectgroup() {
        return subjectgroup;
    }

    /**
     * Gets the value of the subjectRoom property.
     *
     * @return possible object is {@link SubjectRoom }
     *
     */
    public Room getSubjectRoom() {
        return subjectRoom != null ? subjectRoom.get() : null;
    }

    /**
     * Gets the value of the flags property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFlags() {
        return flags;
    }

    /**
     * Gets the value of the subjectDescription property.
     *
     * @return possible object is {@link SubjectDescription }
     *
     */
    public Description getSubjectDescription() {
        return subjectDescription != null ? subjectDescription.get() : null;
    }

    /**
     * Gets the value of the foreignkey property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForeignkey() {
        return foreignkey;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SubjectRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Subject subject;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Subject get() {
            return subject;
        }

    }
}
