//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.document.Marker;
import org.thespheres.betula.document.util.MarkerAdapter.XmlMarkerAdapter;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;

@XmlAccessorType(XmlAccessType.FIELD)
public class Subject {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String longname;
    protected String alias;
    protected String text;
    protected String subjectgroup;
    @XmlElement(name = "subject_room")
    protected RoomRef subjectRoom;
    protected String flags;
    @XmlElement(name = "subject_description")
    protected DescriptionRef subjectDescription;
    protected String foreignkey;
    @XmlJavaTypeAdapter(XmlMarkerAdapter.class)
    @XmlElement(name = "subject", namespace = "http://www.thespheres.org/xsd/betula/betula.xsd")
    protected Marker mappedSubject;

    public String getId() {
        return id;
    }

    public String getLongName() {
        return longname;
    }

    public String getAlias() {
        return alias;
    }

    public String getText() {
        return text;
    }

    public String getSubjectGroup() {
        return subjectgroup;
    }

    public Room getSubjectRoom() {
        return subjectRoom != null ? subjectRoom.get() : null;
    }

    public String getFlags() {
        return flags;
    }

    public Description getSubjectDescription() {
        return subjectDescription != null ? subjectDescription.get() : null;
    }

    public String getForeignKey() {
        return foreignkey;
    }

    public Marker getMappedSubject() {
        return mappedSubject;
    }

    public void setMappedSubject(final Marker subject) {
        this.mappedSubject = subject;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SubjectRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Subject subject;

        public Subject get() {
            return subject;
        }

    }
}
