//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.thespheres.betula.gpuntis.xml.Department.DepartmentRef;
import org.thespheres.betula.gpuntis.xml.Description.DescriptionRef;
import org.thespheres.betula.gpuntis.xml.Room.RoomRef;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Teacher {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String forename;
    protected String surname;
    protected String alias;
    protected String title;
    protected String gender;
    protected String birthdate;
    protected String status;
    protected String payrollnumber;
    protected String email;
    protected String phone;
    protected String text;
    @XmlElement(name = "teacher_room")
    protected RoomRef teacherRoom;
    protected String flags;
    @XmlElement(name = "teacher_description")
    protected DescriptionRef teacherDescription;
    @XmlElement(name = "teacher_department")
    protected DepartmentRef teacherDepartment;
    protected String foreignkey;
    @XmlElement(name = "external_name")
    protected String externalName;
    protected String weektarget;

    public String getId() {
        return id;
    }

    public String getForename() {
        return forename;
    }

    public String getSurname() {
        return surname;
    }

    public String getAlias() {
        return alias;
    }

    public String getTitle() {
        return title;
    }

    public String getGender() {
        return gender;
    }

    public String getBirthdate() {
        return birthdate;
    }

    public String getStatus() {
        return status;
    }

    public String getPayrollnumber() {
        return payrollnumber;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public String getText() {
        return text;
    }

    public Room getTeacherRoom() {
        return teacherRoom != null ? teacherRoom.get() : null;
    }

    public String getFlags() {
        return flags;
    }

    public Description getTeacherDescription() {
        return teacherDescription != null ? teacherDescription.get() : null;
    }

    public Department getTeacherDepartment() {
        return teacherDepartment != null ? teacherDepartment.get() : null;
    }

    public String getForeignkey() {
        return foreignkey;
    }

    public String getExternalName() {
        return externalName;
    }

    public String getWeektarget() {
        return weektarget;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 43 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Teacher other = (Teacher) obj;
        return Objects.equals(this.id, other.id);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TeacherRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Teacher teacher;

        public Teacher get() {
            return teacher;
        }

    }
}
