//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Term {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    protected String begindate;
    protected String enddate;


    public String getId() {
        return id;
    }

    public String getBegindate() {
        return begindate;
    }

    /**
     * Gets the value of the enddate property.
     *
     * @return possible object is {@link Enddate }
     *
     */
    public String getEnddate() {
        return enddate;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TermRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Term subject;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link Object }
         *
         */
        public Term get() {
            return subject;
        }

    }

}
