//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 08:09:46 PM CEST 
//
package org.thespheres.betula.gpuntis.xml;

import org.thespheres.betula.gpuntis.xml.util.TimeAdapter;
import java.time.DayOfWeek;
import java.time.LocalTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Timeperiod {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElement(required = true)
    protected int day;
    @XmlElement(required = true)
    protected int period;
    @XmlJavaTypeAdapter(TimeAdapter.class)
    @XmlElement(required = true)
    protected LocalTime starttime;
    @XmlJavaTypeAdapter(TimeAdapter.class)
    @XmlElement(required = true)
    protected LocalTime endtime;
    @XmlElement
    protected String timegrid;
    protected String label;
    protected String foreignkey;

    public String getId() {
        return id;
    }

    public DayOfWeek getDay() {
        return DayOfWeek.of(day);
    }

    public int getPeriod() {
        return period;
    }

    public LocalTime getStarttime() {
        return starttime;
    }

    public LocalTime getEndtime() {
        return endtime;
    }

    public String getLabel() {
        return label;
    }

    public String getForeignkey() {
        return foreignkey;
    }

    public String getTimegrid() {
        return timegrid;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TimeperiodRef {

        @XmlAttribute(name = "id", required = true)
        @XmlIDREF
        protected Timeperiod description;

        public Timeperiod get() {
            return description;
        }

    }
}
