//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.21 at 11:42:49 PM CEST 
//
package org.thespheres.betula.classtest.xml;

import java.util.Objects;
import org.thespheres.betula.classtest.Basket;

/**
 *
 * @author boris.heithecker
 */
public class XmlProblemRef implements Basket.Ref<Double> {

    protected final XmlProblem reference;
    private Double weight;
    private int position;

    XmlProblemRef(XmlProblem reference) {
        this.reference = reference;
        weight = 1.0d;
    }

    XmlProblemRef(XmlProblem reference, int pos) {
        this(reference);
        position = pos;
    }

    @Override
    public Double getWeight() {
        return weight;
    }

    @Override
    public void setWeight(Double value) {
        this.weight = value;
    }

    @Override
    public String getDisplayName() {
        return reference.getDisplayName();
    }

    @Override
    public void setDisplayName(String displayName) {
        reference.setDisplayName(displayName);
    }

    @Override
    public String getId() {
        return reference.getId();
    }

    @Override
    public int getIndex() {
        return position;
    }

    @Override
    public void setIndex(int index) throws UnsupportedOperationException {
        throw new UnsupportedOperationException("Not supported.");
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.reference);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final XmlProblemRef other = (XmlProblemRef) obj;
        return Objects.equals(this.reference, other.reference);
    }

}
