/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thespheres.betula.noten.ui.classtest;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXComboBox;
import org.jdesktop.swingx.renderer.DefaultListRenderer;
import org.jdesktop.swingx.renderer.StringValue;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;
import org.thespheres.betula.assess.AssessmentContext;

@Messages("NotenClasstestIterator.step1.name=Datei")
public final class NotenClasstestVisualPanel extends JPanel {

    final DefaultComboBoxModel contextModel = new DefaultComboBoxModel(NotenClasstestWizardIterator.CONTEXTS);
    private final StringValue contextStringValue = v -> ((AssessmentContext.Factory) v).getDisplayName();

    /**
     * Creates new form NotenClasstestVisualPanel1
     */
    public NotenClasstestVisualPanel() {
        initComponents();
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(NotenClasstestVisualPanel.class, "NotenClasstestIterator.step1.name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseContextLbl = new javax.swing.JLabel();

        chooseContextLbl.setLabelFor(chooseContextCbx);
        org.openide.awt.Mnemonics.setLocalizedText(chooseContextLbl, org.openide.util.NbBundle.getMessage(NotenClasstestVisualPanel.class, "NotenClasstestVisualPanel.chooseContextLbl.text")); // NOI18N

        chooseContextCbx.setModel(contextModel);
        chooseContextCbx.setRenderer(new DefaultListRenderer(contextStringValue));

        org.openide.awt.Mnemonics.setLocalizedText(reportsCb, org.openide.util.NbBundle.getMessage(NotenClasstestVisualPanel.class, "NotenClasstestVisualPanel.reportsCb.text")); // NOI18N
        reportsCb.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseContextLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseContextCbx, 0, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportsCb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseContextLbl)
                    .addComponent(chooseContextCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reportsCb)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    final javax.swing.JComboBox chooseContextCbx = new JXComboBox();
    private javax.swing.JLabel chooseContextLbl;
    final javax.swing.JCheckBox reportsCb = new javax.swing.JCheckBox();
    // End of variables declaration//GEN-END:variables

}
