/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thespheres.betula.niedersachsen.admin.ui.bemerkungen;

import org.apache.commons.lang3.StringUtils;
import org.thespheres.betula.niedersachsen.zeugnis.TermReportNoteSetTemplate.Element;

/**
 *
 * @author boris.heithecker
 */
class ElementSettingsPanel extends javax.swing.JPanel {

    ElementSettingsPanel(final Element source) {
        initComponents();
        this.nameTextField.setText(source.getElementDisplayName());
        this.multipleSelectionCheckBox.setSelected(source.isMultiple());
        this.nillableCheckBox.setSelected(!source.isNillable());
        multipleSelectionChanged(null);
    }

    public boolean isMultipleSelection() {
        return multipleSelectionCheckBox.isSelected();
    }

    public boolean isNillable() {
        return nillableCheckBox.isSelected();
    }

    public String getNameValue() {
        return StringUtils.stripToNull(nameTextField.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new org.jdesktop.swingx.JXTextField();
        nameLabel = new org.jdesktop.swingx.JXLabel();
        multipleSelectionCheckBox = new javax.swing.JCheckBox();
        nillableCheckBox = new javax.swing.JCheckBox();

        nameTextField.setColumns(100);

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(ElementSettingsPanel.class, "ElementSettingsPanel.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(multipleSelectionCheckBox, org.openide.util.NbBundle.getMessage(ElementSettingsPanel.class, "ElementSettingsPanel.multipleSelectionCheckBox.text")); // NOI18N
        multipleSelectionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleSelectionChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(nillableCheckBox, org.openide.util.NbBundle.getMessage(ElementSettingsPanel.class, "ElementSettingsPanel.nillableCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multipleSelectionCheckBox)
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nillableCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multipleSelectionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nillableCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void multipleSelectionChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleSelectionChanged
        nillableCheckBox.setEnabled(!isMultipleSelection());
    }//GEN-LAST:event_multipleSelectionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox multipleSelectionCheckBox;
    private org.jdesktop.swingx.JXLabel nameLabel;
    private org.jdesktop.swingx.JXTextField nameTextField;
    private javax.swing.JCheckBox nillableCheckBox;
    // End of variables declaration//GEN-END:variables
}
